[profile.default]
src = 'src'
out = 'out'
test = 'src/test'
script = 'src/script'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']
evm_version = 'shanghai'

solc_version = "0.8.20"
extra_output_files = ["metadata"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "${RPC_MAINNET}" 
arbitrum = "${RPC_ARBITRUM}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config